# Generated by Django 3.1.6 on 2021-02-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
