# Generated by Django 3.1.6 on 2021-02-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210205_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='not delivered', max_length=10, null=True),
        ),
    ]
