# Generated by Django 3.1.6 on 2021-02-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
