# Generated by Django 3.1.6 on 2021-02-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
                ('reserverd', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payment Details'},
        ),
    ]
