# Generated by Django 3.1.6 on 2021-02-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approved',
            field=models.BooleanField(default=False,null=True),
        ),
    ]
