# Generated by Django 3.1.6 on 2021-02-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name_plural': 'Notifications    '},
        ),
        migrations.AlterField(
            model_name='notifications',
            name='seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
