# Generated by Django 3.1.6 on 2021-02-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_orders_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
